country:
 defaultlimit: 5
 resolver:
  url: http://ip-api.com/json/
badwords: badword1,badword2,badword3
logging:
  pattern:
    console: '%date - [%level] - %logger %thread %X{transId} %n%message%n%xException%n'
  level:
   ROOT: info