/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'artjom' at '27/03/17 21:23' with Gradle 2.7
 *
 * @author artjom, @date 27/03/17 21:23
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
